### ISSUE TITLE
JS_Parse_Error when using UglifyJSPlugin

### ISSUE THREAD

**Issue by jgraup** [fuse-box/fuse-box-vue-seed#1]
Pardon me, I'm just getting started w/Fuse Box & Vue for that matter, so this may be [straightforward](https://github.com/mishoo/UglifyJS2/issues/348). What I am trying to achieve is minification as described in the [docs](http://fuse-box.org/#uglifyjsplugin). Unfortunately I am getting an error when I try to run with the recommended [UglifyJS2 plugin](https://github.com/mishoo/UglifyJS2). 

How do I go about starting with this seed along with minification?

Thanks for your time.

---

### npm start
```
$ npm run start

> fuse-box-vue-seed@1.0.0 start /fuse-box-vue-seed-master
> node ./fuse.js

19:29:37 : Launching dev server on port 4445
└── default (4 files,  2.5 kB)
      main.js
      app-template.html
      main.scss
      index.html
└── fusebox-hot-reload@0.0.0 (0 files) 1.2 kB
└── fusebox-websocket@0.0.0 (0 files) 2.5 kB
└── events@0.0.0 (0 files) 9.8 kB
└── vue@2.1.10 (0 files) 219.1 kB

    Bundle
    Size: 235.2 kB
    Time: 51ms
Error
    at new JS_Parse_Error (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1
547:18)
    at js_error (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)
    at unexpected (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)
    at semicolon (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2128:56)
    at simple_statement (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:231
9:73)
    at eval (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2188:19)
    at eval (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)
    at block_ (eval at <anonymous> (/fuse-box-vue-seed-master/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2434:20)
19:29:41 : Client connected
19:29:42 : Client connected
```

### fuse.js
```
const fsbx = require('fuse-box');

const fuseBox = fsbx.FuseBox.init({
    homeDir: 'src/',
    sourceMap: {
        bundleReference: 'app.js.map',
        outFile: './dist/app.js.map'
    },
    outFile: './dist/app.js',
    plugins: [
        [
            fsbx.SassPlugin({ outputStyle: 'compressed' }),
            fsbx.CSSPlugin({})
        ],
        fsbx.TypeScriptHelpers(),
        fsbx.UglifyJSPlugin({ outFileName: './dist/app.min.js' }),
        fsbx.JSONPlugin(),
        fsbx.HTMLPlugin({ useDefault: false })
    ]
});

fuseBox.devServer('>main.ts **/*.html', {
    port: 4445
});
```

**Comment by nchanged** [comment]
Welcome @jgraup 
Make sure you have your typescript in es5 mode. UglifyJS does not like pretty code ;-)

**Comment by jgraup** [comment]
Thanks @nchanged. 

Do I add that in a `tsconfig.json` or directly in the `fsbx.TypeScriptHelpers()` arguments within `FuseBox.init`?

**Comment by nchanged** [comment]
Please add ts tsconfig.json  :)

**Comment by edjroot** [comment]
@jgraup, just to make it clearer, UglifyJS doesn't support ES6+ code ([yet](https://github.com/mishoo/UglifyJS2/issues/448)). Babel has a relatively new project that does this: [Babili](https://github.com/babel/babili). I'm new to FuseBox and don't know how to make the two work together, though.

**Comment by jgraup** [comment]
Thanks @edjroot . 

@nchanged, This the first time I'm messing with compiling for `ES6/5` which is why FuseBox is so appealing if it just works. I tried to modify a line in the `tsconfig.json` to compile to `es5` mode but I don't have an experience to know why it is still giving the similar errors. I assume this is set in the `target` section? This isn't anything mission critical, just testing news ways of doing things, so thanks for your time so far.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "isolatedModules": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "noImplicitAny": true,
    "noImplicitUseStrict": false,
    "strictNullChecks": true,
    "noEmitHelpers": true,
    "noLib": false,
    "outDir": "dist/"
  }
}
```

**Comment by nchanged** [comment]
@jgraup these are the steps:
1) Clean the cache (`.fusebox` folder)
2) Make sure you are calling `.bundle` not `devServer`
3) Run it again ;-)

**Comment by devmondo** [comment]
@jgraup  also, be aware, uglfyjs is cumbersome on large files, also we have third party closure compiler plugin, choose your poison :)

**Comment by jgraup** [comment]
Awesome. @nchanged - that was it. Just needed to clear the cache. 

Could that be a command wrapped up in the package.json scripts along with `start`?

**Comment by jgraup** [comment]
Thanks @nchanged, @devmondo & @edjroot for your help. I'm looking forward to this project progressing.
