### ISSUE TITLE
devtool support

### ISSUE THREAD

**Issue by davidm-public** [fuse-box/fuse-box-vue-seed#13]
just came across fusebox today, very nice, love the TS support.
But... not seeing components or store show up in devtools?
Does this project have Devtool support?

**Comment by nchanged** [comment]
Hi, I am not sure, can you paste a link?

**Comment by davidm-public** [comment]
actually I think it showed up in the end, at this point it's the least of my problems!
upgrading the dependencies in this project `salita --update` seems to have broken several things.
Not sure where to start even explaining all the issues!

**Comment by davidm-public** [comment]
am closing this issue for now
