### ISSUE TITLE
Full .vue file / vue-loader support?

### ISSUE THREAD

**Issue by shshaw** [fuse-box/fuse-box-vue-seed#2]
Does this seed and/or Fuse Box itself support .vue file loading with `<template>`, `<script>` and `<style>` in one file? The example only shows loading the HTML separately.

**Comment by devmondo** [comment]
@shshaw  welcome man, soon we will Vue compile plugin, hang in there it is coming :)

**Comment by shshaw** [comment]
I'm definitely interested in a real alternative to Webpack, especially supporting Vue. 

I mostly do front-end JS and not node-specific JS, but if I can contribute please let me know.

**Comment by edjroot** [comment]
Thanks for this awesome project!

I'm very interested in this, too. Is there any way we can contribute?

**Comment by nchanged** [comment]
Thanks!
Any help is greatly appreciated! you can join gitter where we could discuss things :)

**Comment by devmondo** [comment]
@edjroot  also you can push Evan You (Vue Js creator) to chime in on this :)

**Comment by edjroot** [comment]
@yyx990803? :)

**Comment by guzgarcia** [comment]
Are you working on this already?

**Comment by devmondo** [comment]
@guzgarcia  wow, 40s! this would never happen with Fuse!

we are hoping to get this done and we wish some help from @yyx990803

**Comment by nchanged** [comment]
@guzgarcia for fuse that would be 600ms without cache, and 50ms with cache. I tweeted to @yyx990803 We really hope he will help us.

**Comment by guzgarcia** [comment]
I hope Evan has time and can help too. This project has a bright future; maybe in the near future I can contribute as well ;).

**Comment by yyx990803** [comment]
FYI I briefly looked at the FuseBox API but don't have time to work on official support at this time. The first step might be refactoring `vue-loader` to extract some common parts to be reused for different use cases, but it could take some time before we get to that.

**Comment by pendar747** [comment]
The single file component in the example doesn't use typescript. Adding `lang='ts'` to it cuases the this typescript error:
```
Default export of the module has or is using private name 'Vue'.
```

**Comment by devmondo** [comment]
@pendar747 we are working on a better vue plugin with community members, soon we will have great results. hang in there :)

**Comment by Shepless** [comment]
@pendar747 We now have `.vue` file support. This seed has been updated - let me know if you have any issues.

@yyx990803 Would be interested to get your thoughts on the implementation if you have the chance.
