### ISSUE TITLE
Adding HMR leads to Vue error

### ISSUE THREAD

**Issue by FlorianWerndl** [fuse-box/fuse-box-vue-seed#4]
If I add HMR I got something like this on reload: [Vue warn]: Cannot find element: #app

**Comment by nchanged** [comment]
Hi @FlorianWerndl 
Vue cannot handle the HMR at the moment, feel free to investigate why and help us solve this issue.

A good starting point would be to read up [here](http://fuse-box.org/page/development#custom-hmr)

**Comment by FlorianWerndl** [comment]
Alright, thanks for the quick reply.

**Comment by Shepless** [comment]
@FlorianWerndl this should now be fully implemented. Let me know if you're still having issues.
