### ISSUE TITLE
Possible regression. Getting a blank page

### ISSUE THREAD

**Issue by paganaye** [fuse-box/fuse-box-vue-seed#5]
Following the instructions I get a blank page on localhost:4444.
If I replace the package.json line 32 from
    "fuse-box": "^2.0.0-beta.22",
to
    "fuse-box": "2.0.0-beta.22",
Then I get the expected sample page.

**Comment by nchanged** [comment]
@paganaye this seed will be rewritten soon with [VueComponentPlugin](http://fuse-box.org/plugins/vuecomponentplugin) 
@Shepless_twitter did a great job to support most of the features from the original Plugin

**Comment by Shepless** [comment]
@paganaye latest version is now pushed. Let me know if you still have problems.
